using Jibo.Cloud.Domain.Models;
using Npgsql;
using NpgsqlTypes;

namespace Jibo.Cloud.Infrastructure.Persistence;

public sealed class PostgreSqlTrustedServerRepository(PostgreSqlCloudStateDataSource dataSource) : ITrustedServerRepository
{
    public async Task<IReadOnlyList<TrustedServerRecord>> ListAsync(bool includeInactive = false, int limit = 250, CancellationToken ct = default)
    { await using var c = await dataSource.Value.OpenConnectionAsync(ct); await using var q = c.CreateCommand(); q.CommandText = """
      SELECT ServerId,CanonicalHost,DisplayName,ServerKind,IsListed,AcceptsPublicConnections,ParticipatesInCloudSync,RequiresHttps,IsTrustRoot,IsActive,Description,RegisteredAtUtc,UpdatedAtUtc,LastSeenAtUtc
      FROM TrustedServers WHERE @all OR IsActive ORDER BY IsTrustRoot DESC,DisplayName,ServerId LIMIT @limit
      """; q.Parameters.AddWithValue("all", includeInactive); q.Parameters.AddWithValue("limit", Math.Clamp(limit, 1, 1000)); var x = new List<TrustedServerRecord>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(Map(r)); return x; }
    public async Task<TrustedServerRecord> UpsertAsync(TrustedServerRecord s, CancellationToken ct = default)
    { ArgumentNullException.ThrowIfNull(s); await using var c = await dataSource.Value.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await using var q = new NpgsqlCommand("""
      INSERT INTO TrustedServers(ServerId,CanonicalHost,DisplayName,ServerKind,IsListed,AcceptsPublicConnections,ParticipatesInCloudSync,RequiresHttps,IsTrustRoot,IsActive,Description,RegisteredAtUtc,UpdatedAtUtc,LastSeenAtUtc)
      VALUES(@id,@host,@name,@kind,@listed,@public,@sync,@https,@root,@active,@description,@registered,@updated,@seen)
      ON CONFLICT(ServerId) DO UPDATE SET CanonicalHost=EXCLUDED.CanonicalHost,DisplayName=EXCLUDED.DisplayName,ServerKind=EXCLUDED.ServerKind,IsListed=EXCLUDED.IsListed,AcceptsPublicConnections=EXCLUDED.AcceptsPublicConnections,ParticipatesInCloudSync=EXCLUDED.ParticipatesInCloudSync,RequiresHttps=EXCLUDED.RequiresHttps,IsTrustRoot=EXCLUDED.IsTrustRoot,IsActive=EXCLUDED.IsActive,Description=EXCLUDED.Description,UpdatedAtUtc=EXCLUDED.UpdatedAtUtc,LastSeenAtUtc=EXCLUDED.LastSeenAtUtc
      """, c, t); q.Parameters.AddWithValue("id", Req(s.ServerId)); q.Parameters.AddWithValue("host", Req(s.CanonicalHost)); q.Parameters.AddWithValue("name", s.DisplayName); q.Parameters.AddWithValue("kind", s.ServerKind); q.Parameters.AddWithValue("listed", s.IsListed); q.Parameters.AddWithValue("public", s.AcceptsPublicConnections); q.Parameters.AddWithValue("sync", s.ParticipatesInCloudSync); q.Parameters.AddWithValue("https", s.RequiresHttps); q.Parameters.AddWithValue("root", s.IsTrustRoot); q.Parameters.AddWithValue("active", s.IsActive); q.Parameters.AddWithValue("description", s.Description); q.Parameters.AddWithValue("registered", s.RegisteredAtUtc); q.Parameters.AddWithValue("updated", s.UpdatedAtUtc); q.Parameters.Add("seen", NpgsqlDbType.TimestampTz).Value = (object?)s.LastSeenAtUtc ?? DBNull.Value; await q.ExecuteNonQueryAsync(ct); await CloudStateRevision.BumpAsync(c, t, ct); await t.CommitAsync(ct); return s; }
    public async Task<IReadOnlyList<TrustedServerAdmissionRecord>> ListAdmissionsAsync(string serverId, int limit = 250, CancellationToken ct = default)
    { await using var c = await dataSource.Value.OpenConnectionAsync(ct); await using var q = c.CreateCommand(); q.CommandText = "SELECT AdmissionId,ServerId,CanonicalHost,ServerKind,Action,ActorDeviceId,ActorFriendlyId,Reason,SignatureAlgorithm,SignatureKeyId,Payload,Signature,CreatedUtc FROM TrustedServerAdmissions WHERE ServerId=@id ORDER BY CreatedUtc DESC LIMIT @limit"; q.Parameters.AddWithValue("id", Req(serverId)); q.Parameters.AddWithValue("limit", Math.Clamp(limit, 1, 1000)); var x = new List<TrustedServerAdmissionRecord>(); await using var r = await q.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) x.Add(MapAdmission(r)); return x; }
    public async Task<TrustedServerAdmissionRecord> AddAdmissionAsync(TrustedServerAdmissionRecord a, CancellationToken ct = default)
    { ArgumentNullException.ThrowIfNull(a); await using var c = await dataSource.Value.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO TrustedServerAdmissions(AdmissionId,ServerId,CanonicalHost,ServerKind,Action,ActorDeviceId,ActorFriendlyId,Reason,SignatureAlgorithm,SignatureKeyId,Payload,Signature,CreatedUtc) VALUES(@id,@server,@host,@kind,@action,@device,@friendly,@reason,@algorithm,@key,@payload,@signature,@created)", c, t); q.Parameters.AddWithValue("id", Req(a.AdmissionId)); q.Parameters.AddWithValue("server", Req(a.ServerId)); q.Parameters.AddWithValue("host", a.CanonicalHost); q.Parameters.AddWithValue("kind", a.ServerKind); q.Parameters.AddWithValue("action", a.Action); Text(q, "device", a.ActorDeviceId); Text(q, "friendly", a.ActorFriendlyId); Text(q, "reason", a.Reason); q.Parameters.AddWithValue("algorithm", a.SignatureAlgorithm); q.Parameters.AddWithValue("key", a.SignatureKeyId); q.Parameters.AddWithValue("payload", a.Payload); q.Parameters.AddWithValue("signature", a.Signature); q.Parameters.AddWithValue("created", a.CreatedUtc); await q.ExecuteNonQueryAsync(ct); await CloudStateRevision.BumpAsync(c, t, ct); await t.CommitAsync(ct); return a; }
    public async Task<bool> RevokeAnchorAsync(string anchor, string? reason, CancellationToken ct = default) { await using var c = await dataSource.Value.OpenConnectionAsync(ct); await using var t = await c.BeginTransactionAsync(ct); await using var q = new NpgsqlCommand("INSERT INTO RevokedIdentityGraphAnchors(Anchor,Reason) VALUES(@anchor,@reason) ON CONFLICT(Anchor) DO UPDATE SET Reason=EXCLUDED.Reason,RevokedUtc=NOW()", c, t); q.Parameters.AddWithValue("anchor", Req(anchor)); Text(q, "reason", reason); var ok = await q.ExecuteNonQueryAsync(ct) > 0; if (ok) await CloudStateRevision.BumpAsync(c, t, ct); await t.CommitAsync(ct); return ok; }
    public async Task<bool> IsAnchorRevokedAsync(string anchor, CancellationToken ct = default) { await using var c = await dataSource.Value.OpenConnectionAsync(ct); await using var q = c.CreateCommand(); q.CommandText = "SELECT EXISTS(SELECT 1 FROM RevokedIdentityGraphAnchors WHERE Anchor=@anchor)"; q.Parameters.AddWithValue("anchor", Req(anchor)); return (bool)(await q.ExecuteScalarAsync(ct) ?? false); }
    private static TrustedServerRecord Map(NpgsqlDataReader r) => new() { ServerId = r.GetString(0), CanonicalHost = r.GetString(1), DisplayName = r.GetString(2), ServerKind = r.GetString(3), IsListed = r.GetBoolean(4), AcceptsPublicConnections = r.GetBoolean(5), ParticipatesInCloudSync = r.GetBoolean(6), RequiresHttps = r.GetBoolean(7), IsTrustRoot = r.GetBoolean(8), IsActive = r.GetBoolean(9), Description = r.GetString(10), RegisteredAtUtc = r.GetFieldValue<DateTimeOffset>(11), UpdatedAtUtc = r.GetFieldValue<DateTimeOffset>(12), LastSeenAtUtc = r.IsDBNull(13) ? null : r.GetFieldValue<DateTimeOffset>(13) };
    private static TrustedServerAdmissionRecord MapAdmission(NpgsqlDataReader r) => new() { AdmissionId = r.GetString(0), ServerId = r.GetString(1), CanonicalHost = r.GetString(2), ServerKind = r.GetString(3), Action = r.GetString(4), ActorDeviceId = r.IsDBNull(5) ? string.Empty : r.GetString(5), ActorFriendlyId = r.IsDBNull(6) ? string.Empty : r.GetString(6), Reason = r.IsDBNull(7) ? null : r.GetString(7), SignatureAlgorithm = r.GetString(8), SignatureKeyId = r.GetString(9), Payload = r.GetString(10), Signature = r.GetString(11), CreatedUtc = r.GetFieldValue<DateTimeOffset>(12) };
    private static void Text(NpgsqlCommand q, string n, string? v) => q.Parameters.Add(n, NpgsqlDbType.Text).Value = (object?)(string.IsNullOrWhiteSpace(v) ? null : v.Trim()) ?? DBNull.Value; private static string Req(string v) => !string.IsNullOrWhiteSpace(v) ? v.Trim() : throw new ArgumentException("Value is required.");
}
